version: '3.7'

volumes:
  prometheus-data:
  influxdb-storage:
  # grafana-data:

services:
  grafana:
    image: grafana/grafana:${grafana_version}
    container_name: grafana
    # restart: unless-stopped
    volumes:
      # - grafana-data:/var/lib/grafana
      - ./../Grafana:/var/lib/grafana:rw
    ports:
      - 3003:3000
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:${prom_version}
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring
 
  node-exporter:
    image: prom/node-exporter:${node_exporter_version}
    container_name: node_exporter
    # restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - 9101:9100
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${cadvisor_version}
    container_name: cadvisor
    # restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8088:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
  
  influxdb:
    image: influxdb:latest
    container_name:  influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=user_0
      - INFLUXDB_ADMIN_PASSWORD=jfo4n7aumuoamldhfjsaf

networks:
  monitoring:
    driver: bridge
    name: monitoring
